### ISSUE TITLE
No possibility to check if session is still valid

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [vmware/vsphere-automation-sdk-java#195]
I found no example or any method how I could figure out if those objects are still valid after time (expiring of the session):

	private VapiAuthenticationHelper vapiAuthHelper;
	private VimAuthenticationHelper  vimAuthHelper;
	private VMware.VMwareConnection vmWareConnection;
	private StubConfiguration sessionStubConfig;

What is the best practise there?
How can I check if those are still valid to prevent to always renew them on each request (takes alot of runtime).

**Comment by MrLoverLoverMMMM** [comment]
current very inefficient implementation:

Before each request to the api:


vmWareConnection.close();					
vapiAuthHelper.logout();					
vimAuthHelper.logout();
...
vimAuthHelper.loginByUsernameAndPassword(
	                        serverDNSOrIPOfVcenter, userNameOfVcenter, passwordOfVcenter);
vapiAuthHelper = new VapiAuthenticationHelper();
sessionStubConfig =
		                    vapiAuthHelper.loginByUsernameAndPassword(
		                        serverDNSOrIPOfVcenter, userNameOfVcenter, passwordOfVcenter, httpConfig);

**Comment by kunal-pmj** [comment]
These helper classes are for for samples execution.  


> Before each request to the api:

> vmWareConnection.close();
> vapiAuthHelper.logout();
> vimAuthHelper.logout();

These are not called after every API request but after every sample execution. A sample may have more than one API call.

Thanks
Kunal

**Comment by MrLoverLoverMMMM** [comment]
OK, but how can I check if a seesion is still valid or can it not expire during an example?

**Comment by mtsvetanov** [comment]
> OK, but how can I check if a seesion is still valid or can it not expire during an example?

There is an API to get the session - https://developer.vmware.com/apis/vsphere-automation/latest/cis/cis/session/

**Comment by MrLoverLoverMMMM** [comment]
We use the java-sdk, is there a way as well?

**Comment by mtsvetanov** [comment]
> We use the java-sdk, is there a way as well?

Yes, the SDK covers all the APIs, search for the Session iface there.
OK, here it is: https://vmware.github.io/vsphere-automation-sdk-java/vsphere/8.0.1.0/vcenter-bindings/com/vmware/cis/Session.html

**Comment by MrLoverLoverMMMM** [comment]
Is there an example code as well / any?

**Comment by karaatanassov** [comment]
[Session:get()](https://vmware.github.io/vsphere-automation-sdk-java/vsphere/8.0.1.0/vcenter-bindings/com/vmware/cis/Session.html#get--) does exactly this.

**Comment by MrLoverLoverMMMM** [comment]
in java?

**Comment by mtsvetanov** [comment]
Yes, this is a link to Java method representing the API. You will receive Unauthenticated exception if the session is no longer valid. Otherwise, it will return information about (valid) session, and will also bump its expiration time due to the activity. Note however that the session can still disappear unexpectedly, for example if the vCenter server (or the vapi-endpoint process on it) is restarted.  

Another option is to handle Unauthenticated on any API invocation your application is doing. If this happens, you need to re-login and repeat the call. The SDK actually has an utility which helps to eliminate the boilerplate code for this at each API invocation spot. It is the https://vmware.github.io/vsphere-automation-sdk-java/vsphere/8.0.1.0/vcenter-bindings/com/vmware/vapi/client/util/DynamicAuthnFilter.html

One has to configure this Decorator on the ApiProvider used by the stubs with something like the following 

`
   ApiProvider apiProvider = connection.getApiProvider();
   ApiProvider authnDecoratedApiProvider = DynamicAuthnFilter(apiProvider, securityContextSupplier, 1000);
   StubFactory stubFactory = new StrubFactory(authnDecoratedApiProvider);
`

The securityContextSupplier instance has to re-create the session and provide SecurityContext for it, which will be used with the retried API invocation. This will be transparent for the code that does the API invocation, and it will just receive the results (even when the session is re-created and the invocation is retried under the hood).

**Comment by MrLoverLoverMMMM** [comment]
and this will automatically renew when needed or ?

**Comment by mtsvetanov** [comment]
Yes, if an API call completes with Unauthenticated, the DynamicAuthnFilter will retry the call with the new SecurityContext (for a newly created session) and the code which did the original invocation will only see the end result (that is the result of the retry). However, you need to configure it per the steps I outlined above, doing the re-login and construction of the new SecurityContext. 

The good thing about it is that you don't have to tackle this concern at every place you are invoking an API operation, rather it is centralized in the filter.

**Comment by MrLoverLoverMMMM** [comment]
from which type is connection in your example code + how to initi it?
How to init the securityContextSupplier?

My code was until now:

`HttpConfiguration httpConfig =  new HttpConfiguration.Builder()
	        	            .setSslConfiguration(buildSslConfiguration(true))
	        	            .getConfig();
			           	
			    	vmWareConnection = new VMwareConnection(serverDNSOrIPOfVcenter, userNameOfVcenter, passwordOfVcenter);
				
					vimAuthHelper = new VimAuthenticationHelper();
					vimAuthHelper.loginByUsernameAndPassword(
	                        serverDNSOrIPOfVcenter, userNameOfVcenter, passwordOfVcenter);
			   
				   	vapiAuthHelper = new VapiAuthenticationHelper();
			    		    	
				
			    	sessionStubConfig =
		                    vapiAuthHelper.loginByUsernameAndPassword(
		                        serverDNSOrIPOfVcenter, userNameOfVcenter, passwordOfVcenter, httpConfig);`
