### ISSUE TITLE
SDK does not Support all IPS of an certain VM

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [vmware/vsphere-automation-sdk-java#197]
```
Identity identityService=vmwareConnection.getVapiAuthHelper().getStubFactory().createStub(Identity.class, vmwareConnection.getSessionStubConfig());
            IdentityTypes.Info vmInfo=identityService.get(vmToLoadId);
          
                      
           vmInfo.getIpAddress();
``` ==> If a vm has 2 ips you can only receive 1 of them. It is needed to return a list of ips.

Reason is that my vms use multiple nics.

**Comment by MrLoverLoverMMMM** [comment]
Alternative please provide a code snipped to load the list of ips for a certain vm.

**Comment by mtsvetanov** [comment]
All IPs of a VM are available via this API - https://developer.vmware.com/apis/vsphere-automation/latest/vcenter/api/vcenter/vm/vm/guest/networking/interfaces/get/

Which maps to the list() method(s) here in the Java SDK - https://vmware.github.io/vsphere-automation-sdk-java/vsphere/8.0.1.0/vcenter-bindings/index.html

**Comment by MrLoverLoverMMMM** [comment]
what is the code snipped therefore?
I used: 

Identity identityService=vmwareConnection.getVapiAuthHelper().getStubFactory().createStub(Identity.class, vmwareConnection.getSessionStubConfig());
IdentityTypes.Info vmInfo=identityService.get(vmToLoadId);

PS: We are premium customer and pay for support.

**Comment by mtsvetanov** [comment]
The API I'm pointing is a different one and is available since 7.0 U2. 

Just create a stub for the interface I pointed and call the list() method. 

P.S. Support at Github is community based. You can see VMware employees are taking the leading role on this. I believe this vSphere Automation SDK for Java is not on the officially supported list by VMware at the moment (i.e. not supported through API and SDK Support today - https://www.vmware.com/support/services/sdk.html).

**Comment by MrLoverLoverMMMM** [comment]
ok, it seems to work, thanks.
Could you explain to me why the rest-api does not support multiple ips?

**Comment by mtsvetanov** [comment]
The one that worked is a REST API as well, it was introduced to cover for the deficiency of the one you originally tried which is limited to a single IP address. I'm not sure if there are plans to deprecate the old one.
