### ISSUE TITLE
Setting PropertyParams when deploying VM from OVF

### ISSUE THREAD

**Issue by BhavyaLNayak** [vmware/vsphere-automation-sdk-java#34]
Hi,

I am using automation SDK to deploy OVF and power on VM . I need to set console-username, console-password by setting the AdditionalParameters to ResourcePoolDeploymentSpec.

I got the AdditionalParameters  from OvfSummary and set the fields for console-username, console- password, and this AdditionalParameters  I am setting to ResourcePoolDeploymentSpec to deploy.

 But I am getting this error "defaultMessage = An error occurred: Could not convert field 'properties' of structure 'com.vmware.vcenter.ovf.property_params',".

below is what I have done.

``OvfSummary` ovfSummary = this.client.ovfLibraryItemService().filter(libItemId, deploymentTarget);
		List<Structure> additionalParams = ovfSummary.getAdditionalParams();		
		for (int i = 0; i < additionalParams.size();) {
			Map<String, DataValue> dataValueFields = additionalParams.get(i)._getDataValue().getFields();
			OptionalValue optionalValue = (OptionalValue) dataValueFields.get("properties");
			ListValue listValue = optionalValue.getList();
			List<DataValue> myDataValueList = listValue.getList();			
			for (int j = 0; j < myDataValueList.size(); j++) {
				StructValue myDataValue = (StructValue) myDataValueList.get(j);
				
				myDataValue.getName();

				if ("console-username".equalsIgnoreCase(myDataValue.getField("id").toString())) {
					myDataValue.setField("value", "Admin");
				} else if ("console-password".equalsIgnoreCase(myDataValue.getField("id").toString())) {
					myDataValue.setField("value", "Admin@123");
				} else if ("varoot-password".equalsIgnoreCase(myDataValue.getField("id").toString())) {
					myDataValue.setField("value", "Admin@123");
				}
			}
			break;
		}

		// Setting the annotation retrieved from the OVF summary.
		deploymentSpec.setAnnotation(ovfSummary.getAnnotation());
		deploymentSpec.setAdditionalParameters(ovfSummary.getAdditionalParams());`

Is there anything additional set up I have to do to get rid of this error?

thanks.

**Comment by cmills2000** [comment]
I am also experiencing this issue using the .NET SDK:

com.vmware.vapi.std.errors.internal_server_error {'messages': [com.vmware.vapi.std.localizable_message {'id': vapi.bindings.method.impl.unexpected, 'default_message': Provider method implementation threw unexpected exception: com.vmware.vapi.std.errors.InternalServerError, 'args': [com.vmware.vapi.std.errors.InternalServerError]}, com.vmware.vapi.std.localizable_message {'id': com.vmware.vdcs.util.unhandled_error, 'default_message': An error occurred: Could not convert field 'properties' of structure 'com.vmware.vcenter.ovf.property_params', 'args': [Could not convert field 'properties' of structure 'com.vmware.vcenter.ovf.property_params']}], 'data':}

I am successfully setting three values in code: **instance-id**, hostname, and **user-data**.  It is interesting to note that since dash ('-') characters are not allowed in symbol names in .net (and probably Java), the  StructValue keys are transformed to use underscores ('_'), so they become **instance_id**, hostname, and **user_data**.

Also interesting to note that performing this operation in the vsphere UI, and inspecting the json posted, the fields use camel case (ie. **instanceId**, hostname, and **userData**).  

`LibraryItem libItemStub = Vapi.CreateStub<LibraryItem>();
            OvfSummary ovfSummary = libItemStub.Filter(libraryItemId, deploymentTarget);

            if (options != null)
            {
                var optionDict = JObject.FromObject(options);

                foreach (IStructure additionalParameter in ovfSummary.GetAdditionalParams())
                {
                    StructValue value = additionalParameter._GetDataValue();
                    if (value.HasField("properties"))
                    {
                        IDataValue datavalue = value.GetFieldValue("properties");
                        if (datavalue is OptionalValue)
                        {
                            OptionalValue optValue = datavalue as OptionalValue;
                            ListValue listValue = optValue.GetList();
                            foreach (StructValue lv in listValue.Where(lv => lv is StructValue))
                            {
                                IDataValue thisValueName = lv.GetFieldValue("id");
                                Console.WriteLine($"Setting {thisValueName} field");
                                IDataValue thisValue = lv.GetFieldValue("value");
                                string key = thisValueName.ToString();
                                string transformedKey = key.Replace('-', '_');

                                if (optionDict.ContainsKey(key))
                                {
                                    object v = optionDict[key];
                                    string vstring = Convert.ToString(v);
                                    lv.SetField("value", vstring);
                                }
                                else if (optionDict.ContainsKey(transformedKey))
                                {
                                    object v = optionDict[transformedKey];
                                    string vstring = Convert.ToString(v);
                                    lv.SetField("value", vstring);
                                }

                            }

                        }

                        break;
                    }
                }
            }

            var annotation = ovfSummary.GetAnnotation();
            var additionalParams = ovfSummary.GetAdditionalParams();

            deploymentSpec.SetAnnotation(annotation);
            deploymentSpec.SetAdditionalParameters(additionalParams);`

**Comment by sjones-vcd** [comment]
Is this issue still active? We are considering using this SDK but if this issue still exists, it will not be an option for us. I was hoping to find out before taking the time to do integration work to consume it.

**Comment by sumitAgrawal007** [comment]
Hi @sjones-vcd 
I will check this and let you know.

**Comment by sumitAgrawal007** [comment]
Hi @sjones-vcd,
I have checked the given sample with the modified code in the latest SDK, and it works fine without any issues.
So this issue is resolved.
